# Generated by Django 3.0.5 on 2020-04-08 06:03
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20200408_0422'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='datetime',
        ),
        migrations.AddField(
            model_name='events',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime.now()),
            preserve_default=False,
        ),
    ]
