# Generated by Django 3.0.5 on 2020-04-08 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20200408_0603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='tags',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
