# Generated by Django 2.2.11 on 2020-04-09 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20200408_0645'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=140)),
                ('status', models.IntegerField(choices=[(1, 'UP'), (2, 'WARN'), (3, 'SLOW'), (4, 'DOWN'), (5, 'OFF')])),
                ('host', models.CharField(max_length=140)),
                ('tags', models.CharField(blank=True, max_length=400, null=True)),
                ('message', models.TextField(blank=True, help_text='Status summary', null=True)),
                ('duration', models.DecimalField(decimal_places=4, max_digits=11)),
                ('date_time', models.DateTimeField(help_text='Actual captured date time')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='incidents',
            name='event',
        ),
        migrations.DeleteModel(
            name='Events',
        ),
        migrations.DeleteModel(
            name='Incidents',
        ),
    ]
