version: "3"

services:
  db:
    image: postgres
    volumes:
      - ./var/lib/postgres-data:/var/lib/postgresql/data
    env_file:
      - .env
  redis:
    image: redis
  web:
    build: .
    command: gunicorn dashboard.wsgi:application --bind 0.0.0.0:8000 --workers 3
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    env_file:
      - .env
  broker:
    build: .
    command: celery -A dashboard worker
    volumes:
      - .:/code
    depends_on:
      - db
      - redis
    env_file:
      - .env
  proxy:
    build: deploy/nginx/.
    depends_on:
      - web
    ports:
      - "80:80"
