# Generated by Django 3.0.5 on 2020-04-08 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organizations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=70)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('country', models.CharField(max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
